version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
  bundle:
    driver: local
